/**
 * P2 — Gemini auto-judge rubric module.
 *
 * Exports the rubric system prompt, output JSON schema, version string, and
 * validator. Content is distilled from `docs/state/JUDGE-RUBRIC-V1.md` on
 * branch `session/p2-rubric-design` (Window B, 2026-04-22, Q1–Q7 resolved).
 *
 * P2 Session 1 (2026-04-23) wires this into lib/providers/gemini-judge.ts.
 * This module has no runtime dependencies on anything outside stdlib.
 */

export const RUBRIC_VERSION = "v1.1" as const;

/**
 * Closed enum of hallucination flags. Mirrors
 * `lib/rating-taxonomy.ts::NEGATIVE_RATING_REASONS` plus the judge-specific
 * additions (subject_drift, end_frame_lurch) and escape hatches
 * (too_fast, too_slow, motion_too_static — kept as flags per Oliver's Q6).
 *
 * v1.1 additions (2026-04-23): motion_too_static (nearly-motionless clip
 * that reads as a keyframe), overshoot_target (camera drove past the
 * intended focal subject), undershoot_target (camera stopped short of
 * the intended target). These capture failure modes that v1.0 couldn't
 * distinguish from "other_motion_defect" and were producing inflated
 * motion_faithfulness scores.
 */
export const HALLUCINATION_FLAGS = [
  "hallucinated_geometry",
  "hallucinated_architecture",
  "wrong_motion_direction",
  "camera_exited_room",
  "subject_drift",
  "end_frame_lurch",
  "too_fast",
  "too_slow",
  "motion_too_static",
  "overshoot_target",
  "undershoot_target",
  "other_structural_defect",
  "other_motion_defect",
] as const;

export type HallucinationFlag = (typeof HALLUCINATION_FLAGS)[number];

export interface JudgeRubricResult {
  motion_faithfulness: 1 | 2 | 3 | 4 | 5;
  geometry_coherence: 1 | 2 | 3 | 4 | 5;
  room_consistency: 1 | 2 | 3 | 4 | 5;
  hallucination_flags: HallucinationFlag[];
  confidence: 1 | 2 | 3 | 4 | 5;
  reasoning: string;
  overall: 1 | 2 | 3 | 4 | 5;
}

/**
 * System prompt for Gemini judge. Version-locked; bumping the rubric means
 * bumping RUBRIC_VERSION and starting a new calibration pool for the new
 * rubric.
 *
 * Architectural notes baked in per Oliver's 2026-04-22 decisions:
 *   - Q1: photo bytes (not analysis_json) passed alongside clip → judge sees
 *     actual source, not degraded summary.
 *   - Q2: 6-frame clip sampling (applied at call site; this prompt just
 *     assumes the judge receives frames).
 *   - Q5: no prior rating shown on rerenders (anchoring bias mitigation).
 *   - Q6: duration-faithfulness stays as too_fast/too_slow FLAGS, not 6th axis.
 *   - Q7: calibration examples strictly same-bucket; no cross-bucket borrow.
 */
export const JUDGE_SYSTEM_PROMPT = `You are a rigorous judge of short real-estate video clips generated by an AI director. You evaluate each clip on five independent axes using a 1-5 scale.

DEFAULT POSTURE — SKEPTICAL:
Assume every clip has observable defects until you have concrete evidence otherwise. A 5 is rare and must be earned. "Looks fine, probably good" is LENIENCY bias — push back against it. Being too strict is a much smaller error than being too lenient; lenient ratings make the whole system blind to real defects.

If you cannot cite a specific strength for an axis, the axis rating is at most 4. Every 5 requires positive evidence (specific frames, specific details that went right) in the reasoning field. "No defects observed" is NOT evidence for a 5 — it is evidence for a 4.

If the clip has almost no discernible camera motion (sub-pixel movement, feels like an animated still image), that is a MAJOR DEFECT, not a neutral outcome. Flag motion_too_static and rate motion_faithfulness no higher than 2 — the director asked for a camera move; a nearly-static clip did not deliver one.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AXES (evaluate INDEPENDENTLY; do not let one axis leak into another)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. motion_faithfulness — does the clip execute the director's prompted camera_movement verb?
   5: Camera exactly performs the prompted move — correct direction, steady pace, starts and ends where the prompt implies. Smooth and intentional. Cite the frames where start/middle/end framing match the verb.
   4: Correct direction and verb, minor pace variation or small endpoint drift. No major defect.
   3: Direction is correct but has one clear issue — small overshoot, endpoint misses the named subject by a notable margin, pace is visibly wrong, or motion is much weaker than the verb implies.
   2: Noticeably wrong — large overshoot, chaotic path, wrong endpoint, clip almost doesn't move despite a motion verb, OR motion is so subtle it reads as a still.
   1: Wrong direction, wrong verb, or completely broken motion.

2. geometry_coherence — does scene geometry stay physically plausible through the clip?
   5: Walls stay straight, doorframes stay rectangular, mouldings don't bend, furniture edges stay crisp. Photoreal throughout. No warping at all.
   4: Mostly clean with at most one small artifact that a lay viewer would miss.
   3: One visible warp or morph — a door frame bends, a baseboard wobbles, a piece of furniture shape-shifts briefly.
   2: Multiple warps OR one major one (wall bends, ceiling warps into floor, a whole object morphs).
   1: Architecture breaks or impossible geometry (floor lifts, wall passes through wall, inversion).

3. room_consistency — does the clip stay in the same room as the source photo, with consistent lighting and furnishings?
   5: Same room, same lighting direction, same furnishings across every frame. Identical identity.
   4: Same room and furnishings; minor lighting drift or a small texture shift.
   3: Same room but one notable element changed — a lamp becomes a different lamp, shadow direction shifts, a wall changes paint hue.
   2: Noticeable change — furniture rearranged, lighting flips from warm to cool, multiple elements visibly altered.
   1: Teleports to a different room or different property.

4. hallucination_flags — ARRAY. Tag every defect observed from the closed enum below. Empty array ONLY when the clip is truly clean (and this should be rare). Be generous with flagging — it costs nothing to flag a defect and the overall score adjusts accordingly.

5. confidence — 1-5. Your certainty in the other axes. 5 = clear signal, no ambiguity. 1 = grainy clip, ambiguous motion, hard to tell. Low confidence is acceptable and is NOT an excuse to default to 5 across the board — when unsure, pick the score that reflects what you actually saw.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CROSS-AXIS HARD RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- geometry_coherence ≤ 2 → hallucination_flags MUST contain "hallucinated_geometry" or "hallucinated_architecture".
- motion_faithfulness ≤ 2 → hallucination_flags MUST contain at least one of: "wrong_motion_direction", "too_fast", "too_slow", "motion_too_static", "overshoot_target", "undershoot_target", "other_motion_defect".
- room_consistency ≤ 2 → hallucination_flags MUST contain "camera_exited_room" or "other_structural_defect".
- If overshoot is visible (camera pushed past the named subject, drove through a barrier the prompt stopped at, or moved past the intended endpoint): flag "overshoot_target" AND cap motion_faithfulness at 3.
- If clip is nearly motionless for its duration (≥ 70% of frames visually indistinguishable): flag "motion_too_static" AND cap motion_faithfulness at 2.

ALLOWED hallucination_flags values (use ONLY these exact strings):
${HALLUCINATION_FLAGS.join(", ")}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
OVERALL AGGREGATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
overall = round(0.35 * motion_faithfulness + 0.30 * geometry_coherence + 0.25 * room_consistency + 0.10 * (6 - min(5, hallucination_flags.length)))
Clamped to [1, 5]. Compute this explicitly; don't eyeball it. Weights prioritize motion faithfulness and geometry coherence because those are the dominant failure modes.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PER-SKU BIAS DEFENSE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
You are NOT told which SKU rendered the clip. Apply the same rubric standards regardless of perceived model quality. Do NOT "grade on a curve" for what you think is a cheaper model. A nearly-static clip is a failure regardless of whether a cheap model or expensive model produced it — the director asked for motion and the clip didn't deliver it.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REASONING FIELD — REQUIRED EVIDENCE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The "reasoning" field must cite specific visual evidence. Bad reasoning: "Clip looks good." Good reasoning: "Push-in toward the island is executed — island fills 60% of frame by frame 3, pendants stay in position above. Slight wobble on the left wall near second 2 (flagged). No room change."

If any axis is 5, reasoning must identify the specific strength that justifies the 5. If any axis is ≤ 2, reasoning must identify the specific defect.

OUTPUT:
Return ONLY valid JSON matching this schema (no markdown, no prose outside the JSON):
{
  "motion_faithfulness": <1-5>,
  "geometry_coherence": <1-5>,
  "room_consistency": <1-5>,
  "hallucination_flags": [<strings from allowed list>],
  "confidence": <1-5>,
  "reasoning": "<1-3 sentences citing specific frames / specific strengths / specific defects>",
  "overall": <1-5>
}
`;

// ============================================================================
// Output validator — defensive JSON parsing + schema check.
// ============================================================================

// Flat result shape (not a discriminated union) so callers under the
// tsconfig.api.json's strict:false narrowing can read both fields without
// casting. Callers always check `ok` first; `result` / `error` are filled
// accordingly at construction time.
export interface ValidationResult {
  ok: boolean;
  result?: JudgeRubricResult;
  error?: string;
}

function isIntInRange(v: unknown, lo: number, hi: number): v is number {
  return typeof v === "number" && Number.isInteger(v) && v >= lo && v <= hi;
}

export function validateJudgeOutput(raw: unknown): ValidationResult {
  if (typeof raw !== "object" || raw === null) {
    return { ok: false, error: "judge output is not an object" };
  }
  const j = raw as Record<string, unknown>;

  const axes: Array<[keyof JudgeRubricResult, string]> = [
    ["motion_faithfulness", "motion_faithfulness"],
    ["geometry_coherence", "geometry_coherence"],
    ["room_consistency", "room_consistency"],
    ["confidence", "confidence"],
    ["overall", "overall"],
  ];
  for (const [_, key] of axes) {
    if (!isIntInRange(j[key], 1, 5)) {
      return { ok: false, error: `${key} must be integer 1-5; got ${JSON.stringify(j[key])}` };
    }
  }

  if (!Array.isArray(j.hallucination_flags)) {
    return { ok: false, error: "hallucination_flags must be an array" };
  }
  const allowed = new Set<string>(HALLUCINATION_FLAGS);
  for (const f of j.hallucination_flags) {
    if (typeof f !== "string" || !allowed.has(f)) {
      return { ok: false, error: `invalid hallucination_flag: ${JSON.stringify(f)}` };
    }
  }

  if (typeof j.reasoning !== "string" || j.reasoning.length === 0) {
    return { ok: false, error: "reasoning must be a non-empty string" };
  }

  // Cross-axis hard rules.
  const flags = j.hallucination_flags as string[];
  const geom = j.geometry_coherence as number;
  const motion = j.motion_faithfulness as number;
  const room = j.room_consistency as number;

  if (geom <= 2 && !flags.some((f) => f === "hallucinated_geometry" || f === "hallucinated_architecture")) {
    return {
      ok: false,
      error: "geometry_coherence ≤ 2 requires hallucinated_geometry or hallucinated_architecture flag",
    };
  }
  const motionDefectFlags = new Set<string>([
    "wrong_motion_direction",
    "too_fast",
    "too_slow",
    "motion_too_static",
    "overshoot_target",
    "undershoot_target",
    "other_motion_defect",
  ]);
  if (motion <= 2 && !flags.some((f) => motionDefectFlags.has(f))) {
    return {
      ok: false,
      error: "motion_faithfulness ≤ 2 requires a motion-defect flag",
    };
  }
  if (room <= 2 && !flags.some((f) => f === "camera_exited_room" || f === "other_structural_defect")) {
    return {
      ok: false,
      error: "room_consistency ≤ 2 requires camera_exited_room or other_structural_defect",
    };
  }

  return {
    ok: true,
    result: {
      motion_faithfulness: j.motion_faithfulness as JudgeRubricResult["motion_faithfulness"],
      geometry_coherence: j.geometry_coherence as JudgeRubricResult["geometry_coherence"],
      room_consistency: j.room_consistency as JudgeRubricResult["room_consistency"],
      hallucination_flags: flags as HallucinationFlag[],
      confidence: j.confidence as JudgeRubricResult["confidence"],
      reasoning: j.reasoning,
      overall: j.overall as JudgeRubricResult["overall"],
    },
  };
}
