/**
 * P2 — Gemini auto-judge rubric module.
 *
 * Exports the rubric system prompt, output JSON schema, version string, and
 * validator. Content is distilled from `docs/state/JUDGE-RUBRIC-V1.md` on
 * branch `session/p2-rubric-design` (Window B, 2026-04-22, Q1–Q7 resolved).
 *
 * P2 Session 1 (2026-04-23) wires this into lib/providers/gemini-judge.ts.
 * This module has no runtime dependencies on anything outside stdlib.
 */

export const RUBRIC_VERSION = "v1.0" as const;

/**
 * Closed enum of hallucination flags. Mirrors
 * `lib/rating-taxonomy.ts::NEGATIVE_RATING_REASONS` plus the judge-specific
 * additions (subject_drift, end_frame_lurch) and two escape hatches
 * (too_fast, too_slow — kept as flags per Oliver's Q6).
 */
export const HALLUCINATION_FLAGS = [
  "hallucinated_geometry",
  "hallucinated_architecture",
  "wrong_motion_direction",
  "camera_exited_room",
  "subject_drift",
  "end_frame_lurch",
  "too_fast",
  "too_slow",
  "other_structural_defect",
  "other_motion_defect",
] as const;

export type HallucinationFlag = (typeof HALLUCINATION_FLAGS)[number];

export interface JudgeRubricResult {
  motion_faithfulness: 1 | 2 | 3 | 4 | 5;
  geometry_coherence: 1 | 2 | 3 | 4 | 5;
  room_consistency: 1 | 2 | 3 | 4 | 5;
  hallucination_flags: HallucinationFlag[];
  confidence: 1 | 2 | 3 | 4 | 5;
  reasoning: string;
  overall: 1 | 2 | 3 | 4 | 5;
}

/**
 * System prompt for Gemini judge. Version-locked; bumping the rubric means
 * bumping RUBRIC_VERSION and starting a new calibration pool for the new
 * rubric.
 *
 * Architectural notes baked in per Oliver's 2026-04-22 decisions:
 *   - Q1: photo bytes (not analysis_json) passed alongside clip → judge sees
 *     actual source, not degraded summary.
 *   - Q2: 6-frame clip sampling (applied at call site; this prompt just
 *     assumes the judge receives frames).
 *   - Q5: no prior rating shown on rerenders (anchoring bias mitigation).
 *   - Q6: duration-faithfulness stays as too_fast/too_slow FLAGS, not 6th axis.
 *   - Q7: calibration examples strictly same-bucket; no cross-bucket borrow.
 */
export const JUDGE_SYSTEM_PROMPT = `You are a rigorous judge of short real-estate video clips generated by an AI director. You evaluate each clip on five independent axes using a 1-5 scale where 5 is ideal and 1 is broken.

AXES (evaluate INDEPENDENTLY; do not let one axis leak into another):

1. motion_faithfulness: How well does the clip's camera motion match the director's prompted camera_movement verb? 5 = exact match, smooth and intentional. 1 = wrong direction or chaotic.

2. geometry_coherence: Does the scene geometry stay physically plausible? Do walls stay straight, doors stay rectangular, ceilings stay above floors? 5 = photoreal through the clip. 1 = architecture warps, floor inverts, impossible spatial transforms.

3. room_consistency: Does the clip stay in the same room as the source photo? Does lighting/style match the source? 5 = same room, same lighting, same era. 1 = teleported to a different property.

4. hallucination_flags: Tag every defect observed from the closed enum below. Empty array is allowed when clip is clean. This field uses ARRAY semantics (not a score); the overall rating below incorporates flag severity.

5. confidence: Your own certainty in the above ratings. 5 = high confidence (clear signal, no ambiguity). 1 = very low confidence (grainy clip, ambiguous motion, edge case). If confidence ≤ 2, set motion_faithfulness / geometry_coherence / room_consistency to your best guess but flag the ambiguity in reasoning.

CROSS-AXIS HARD RULES:
- If geometry_coherence ≤ 2, hallucination_flags MUST contain either "hallucinated_geometry" or "hallucinated_architecture".
- If motion_faithfulness ≤ 2, hallucination_flags MUST contain either "wrong_motion_direction" or a too_fast/too_slow/other_motion_defect flag.
- If room_consistency ≤ 2, hallucination_flags MUST contain "camera_exited_room" or "other_structural_defect".

ALLOWED hallucination_flags values (use ONLY these strings):
${HALLUCINATION_FLAGS.join(", ")}

OVERALL AGGREGATION:
overall = round(0.35 * motion_faithfulness + 0.30 * geometry_coherence + 0.25 * room_consistency + 0.10 * (6 - min(5, hallucination_flags.length)))
Clamped to [1, 5]. Weights prioritize motion faithfulness (what the director controls) and geometry coherence (the dominant failure mode). Hallucination count penalizes multi-defect clips.

PER-SKU BIAS DEFENSE (Q2 in rubric design):
You are NOT told which SKU rendered the clip. Apply the same rubric standards regardless of perceived model quality. Do not "grade on a curve" for what you think is a cheaper model.

OUTPUT:
Return ONLY valid JSON matching this schema (no markdown, no prose outside the JSON):
{
  "motion_faithfulness": <1-5>,
  "geometry_coherence": <1-5>,
  "room_consistency": <1-5>,
  "hallucination_flags": [<strings from allowed list>],
  "confidence": <1-5>,
  "reasoning": "<1-3 sentences citing specific frames or defects>",
  "overall": <1-5>
}
`;

// ============================================================================
// Output validator — defensive JSON parsing + schema check.
// ============================================================================

export interface ValidationOk {
  ok: true;
  result: JudgeRubricResult;
}
export interface ValidationErr {
  ok: false;
  error: string;
}
export type ValidationResult = ValidationOk | ValidationErr;

function isIntInRange(v: unknown, lo: number, hi: number): v is number {
  return typeof v === "number" && Number.isInteger(v) && v >= lo && v <= hi;
}

export function validateJudgeOutput(raw: unknown): ValidationResult {
  if (typeof raw !== "object" || raw === null) {
    return { ok: false, error: "judge output is not an object" };
  }
  const j = raw as Record<string, unknown>;

  const axes: Array<[keyof JudgeRubricResult, string]> = [
    ["motion_faithfulness", "motion_faithfulness"],
    ["geometry_coherence", "geometry_coherence"],
    ["room_consistency", "room_consistency"],
    ["confidence", "confidence"],
    ["overall", "overall"],
  ];
  for (const [_, key] of axes) {
    if (!isIntInRange(j[key], 1, 5)) {
      return { ok: false, error: `${key} must be integer 1-5; got ${JSON.stringify(j[key])}` };
    }
  }

  if (!Array.isArray(j.hallucination_flags)) {
    return { ok: false, error: "hallucination_flags must be an array" };
  }
  const allowed = new Set<string>(HALLUCINATION_FLAGS);
  for (const f of j.hallucination_flags) {
    if (typeof f !== "string" || !allowed.has(f)) {
      return { ok: false, error: `invalid hallucination_flag: ${JSON.stringify(f)}` };
    }
  }

  if (typeof j.reasoning !== "string" || j.reasoning.length === 0) {
    return { ok: false, error: "reasoning must be a non-empty string" };
  }

  // Cross-axis hard rules.
  const flags = j.hallucination_flags as string[];
  const geom = j.geometry_coherence as number;
  const motion = j.motion_faithfulness as number;
  const room = j.room_consistency as number;

  if (geom <= 2 && !flags.some((f) => f === "hallucinated_geometry" || f === "hallucinated_architecture")) {
    return {
      ok: false,
      error: "geometry_coherence ≤ 2 requires hallucinated_geometry or hallucinated_architecture flag",
    };
  }
  if (motion <= 2 && !flags.some((f) => f === "wrong_motion_direction" || f === "too_fast" || f === "too_slow" || f === "other_motion_defect")) {
    return {
      ok: false,
      error: "motion_faithfulness ≤ 2 requires a motion-defect flag",
    };
  }
  if (room <= 2 && !flags.some((f) => f === "camera_exited_room" || f === "other_structural_defect")) {
    return {
      ok: false,
      error: "room_consistency ≤ 2 requires camera_exited_room or other_structural_defect",
    };
  }

  return {
    ok: true,
    result: {
      motion_faithfulness: j.motion_faithfulness as JudgeRubricResult["motion_faithfulness"],
      geometry_coherence: j.geometry_coherence as JudgeRubricResult["geometry_coherence"],
      room_consistency: j.room_consistency as JudgeRubricResult["room_consistency"],
      hallucination_flags: flags as HallucinationFlag[],
      confidence: j.confidence as JudgeRubricResult["confidence"],
      reasoning: j.reasoning,
      overall: j.overall as JudgeRubricResult["overall"],
    },
  };
}
