// DRAFT — GENERATED BY scripts/build-router-table.ts
// Generated: 2026-04-21T19:08:02.677Z
//
// NOT WIRED INTO lib/providers/router.ts. Round 2 decides whether
// to promote this draft based on the coverage report alongside.
//
// Winner rule: >=3 iterations in (room_type, camera_movement) bucket
// AND >=80% rated >=4*. Tiebreak: higher avg rating, then cheaper
// per-clip cost. SKU-level signal currently lives only on
// prompt_lab_listing_scene_iterations (Phase 2.8). Legacy Lab and
// prod scene_ratings contribute provider-level context only.

import type { VideoProvider } from "../db.js";

export interface RouterTableRow {
  room_type: string;
  camera_movement: string;
  provider: VideoProvider;
  sku: string;
  modelKey?: string; // for atlas routes
  win_rate: number;  // 0-1, fraction of iterations rated >=4*
  iter_count: number;
  avg_rating: number;
}

export const ROUTER_TABLE_DRAFT: ReadonlyArray<RouterTableRow> = [
  // (no buckets met the winner threshold with current signal)
];

export function lookupRouterRow(
  roomType: string,
  cameraMovement: string,
): RouterTableRow | undefined {
  return ROUTER_TABLE_DRAFT.find(
    (r) => r.room_type === roomType && r.camera_movement === cameraMovement,
  );
}
